### ISSUE TITLE
blinking while changing focus on window

### ISSUE THREAD

**Issue by mosheavni** [nvim-zh/colorful-winsep.nvim#19] opened 2022-11-13 11:49 UTC
While changing focus on a window, there's a minor blinking.
What can be the cause?

https://user-images.githubusercontent.com/17252601/201520186-451c543a-5631-45b8-9d09-3792362310d1.mp4

**Comment by denstiny** [comment] 2022-11-13 13:53
Is the minimal config startup still there, I'm guessing it's because of the null-ls

**Comment by denstiny** [comment] 2022-11-13 14:35
https://github.com/nvim-zh/colorful-winsep.nvim/commit/f22dfb4533ac5a7f4b59b002f9e4a748c2f72582
I think this will work

**Comment by LamprosPitsillos** [comment] 2022-11-14 09:46
On the latest version , blinking is still visible

**Comment by denstiny** [comment] 2022-11-14 14:33
![图片](https://user-images.githubusercontent.com/57088952/201686258-192d8c44-4f73-44c2-99f7-c823e53f6e4f.png)
How can I have this floating window

**Comment by LamprosPitsillos** [comment] 2022-11-14 14:45
since OP didnt post any info:
My version is  :
```
NVIM v0.9.0-dev-288+g69507c020
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by inferno@InfernoPC

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/usr/local/share/nvim"

Run :checkhealth for more info

```
I don't use null-ls nor the plugin used is the above picture.

**Comment by denstiny** [comment] 2022-11-14 14:50
> 

Ok, I'm glad you can reply in time, I will check and clear it

**Comment by LamprosPitsillos** [comment] 2022-11-14 14:57
https://user-images.githubusercontent.com/61395246/201692016-718d9d49-0684-4433-b9bf-c16867093836.mp4

Strange.. it seems to be scrolling the buffer on its own.. I just switch windows an the scrolling happens on its own

**Comment by LamprosPitsillos** [comment] 2022-11-14 15:01
Sorry, i thought it might be related to the issue

**Comment by denstiny** [comment] 2022-11-14 15:07
> Sorry, i thought it might be related to the issue

This should be a compatibility issue with other plug-ins, what plug-ins are on the video

**Comment by denstiny** [comment] 2022-11-14 15:41
@LamprosPitsillos  @mosheavn Can you provide a minimal reproducible configuration, I can't reproduce

**Comment by LamprosPitsillos** [comment] 2022-11-14 15:59
Tried a minimal conf , i also cant reproduce it ...
@mosheavni can we both post our plugins to find what might case it?
I used the minimal conf from `nvim-cmp`:
```vim
if has('vim_starting')
  set encoding=utf-8
endif
scriptencoding utf-8

if &compatible
  set nocompatible
endif

let s:plug_dir = expand('/tmp/plugged/vim-plug')
if !filereadable(s:plug_dir .. '/plug.vim')
  execute printf('!curl -fLo %s/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim', s:plug_dir)
end

execute 'set runtimepath+=' . s:plug_dir
call plug#begin(s:plug_dir)
Plug 'hrsh7th/nvim-cmp'
Plug 'hrsh7th/cmp-buffer'
Plug 'hrsh7th/cmp-nvim-lsp'
Plug 'hrsh7th/vim-vsnip'
Plug 'neovim/nvim-lspconfig'
Plug 'nvim-zh/colorful-winsep.nvim'
Plug 'navarasu/onedark.nvim'
Plug "lewis6991/gitsigns.nvim"
call plug#end()
PlugInstall | quit

" Setup global configuration. More on configuration below.
lua << EOF
local cmp = require "cmp"
cmp.setup {
  snippet = {
    expand = function(args)
      vim.fn["vsnip#anonymous"](args.body)
    end,
  },

  mapping = {
    ['<CR>'] = cmp.mapping.confirm({ select = true })
  },

  sources = cmp.config.sources({
    { name = "nvim_lsp" },
    { name = "buffer" },
  }),
}
EOF

lua << EOF
local capabilities = require('cmp_nvim_lsp').default_capabilities()

require'lspconfig'.cssls.setup {
  capabilities = capabilities,
}
 require('colorful-winsep').setup()
EOF

```

```lua
{
    function(use)
        use("L3MON4D3/LuaSnip")
        use("akinsho/toggleterm.nvim")
        use("ethanholz/nvim-lastplace")
        use("goolord/alpha-nvim")
        use("nat-418/boole.nvim")
        use("p00f/clangd_extensions.nvim")
      
        use({ "hrsh7th/nvim-cmp",
            requires = {
                "L3MON4D3/LuaSnip",
                "hrsh7th/cmp-buffer",
                "hrsh7th/cmp-cmdline",
                "hrsh7th/cmp-nvim-lsp",
                "hrsh7th/cmp-nvim-lsp-signature-help",
                -- "hrsh7th/cmp-nvim-lua",
                "hrsh7th/cmp-path",
                "saadparwaiz1/cmp_luasnip",
                "tamago324/cmp-zsh",
                "onsails/lspkind-nvim",
            },
        })
        use("lewis6991/gitsigns.nvim")
        use("lewis6991/impatient.nvim")
        use("mcauley-penney/tidy.nvim")
        use("echasnovski/mini.nvim")
        use("nathom/filetype.nvim")
        use("navarasu/onedark.nvim")
        use("neovim/nvim-lspconfig")
        use("numToStr/Comment.nvim")
        use("nvim-lua/plenary.nvim")
        use("nvim-lua/popup.nvim")
        use("nvim-neorg/neorg")
        use("rcarriga/nvim-notify")
        use({
            "folke/todo-comments.nvim",
            requires = "nvim-lua/plenary.nvim",
        })

        use("ThePrimeagen/harpoon")
        use({ "nvim-telescope/telescope.nvim", requires = {
            "/home/inferno/docs/Programming/Projects/telescope-zoxide",
            "nvim-telescope/telescope-ui-select.nvim",
            "nvim-telescope/telescope-file-browser.nvim",
            "nvim-treesitter/nvim-treesitter-textobjects",
            "benfowler/telescope-luasnip.nvim",
            { "nvim-telescope/telescope-fzf-native.nvim", run = "make" }

        } })
        use("nvim-treesitter/playground")
        use "lukas-reineke/indent-blankline.nvim"
        use { "rcarriga/nvim-dap-ui", requires = { "mfussenegger/nvim-dap" } }
        use("catppuccin/nvim")
        use("olimorris/onedarkpro.nvim")
        use("p00f/nvim-ts-rainbow")
        use("rafamadriz/friendly-snippets")
        use("kyazdani42/nvim-web-devicons")
        use("wbthomason/packer.nvim")
        use("windwp/nvim-autopairs")
        use({ "nvim-treesitter/nvim-treesitter-context", requires = { "nvim-treesitter" } })
        use({ "hoob3rt/lualine.nvim", requires = { "kyazdani42/nvim-web-devicons", opt = true, }, })
        use("uga-rosa/ccc.nvim")
        use({ "nvim-treesitter/nvim-treesitter", run = ":TSUpdate" })
        use({ "s1n7ax/nvim-comment-frame", requires = { "nvim-treesitter" } })
        use({ "akinsho/bufferline.nvim", requires = "kyazdani42/nvim-web-devicons" })
        use({ "m-demare/attempt.nvim", requires = "nvim-lua/plenary.nvim" })
    end,
    config = {
        display = {
            open_fn = require("packer.util").float,
        },
        profile = {
            enable = false,
        }
    },
}
```

**Comment by LamprosPitsillos** [comment] 2022-11-16 09:40
I've been trying for 2 days and still can't reproduce it... Sorry

**Comment by denstiny** [comment] 2022-11-16 18:11
> 
I think I can directly use the complete configuration testing

**Comment by 3rd** [comment] 2022-11-16 21:23
Same issue, maybe it's because of some option instead of a plugin conflict :-?

**Comment by denstiny** [comment] 2022-11-17 05:58
> Same issue, maybe it's because of some option instead of a plugin conflict :-?
Please provide your minimum recurring configuration

**Comment by jemag** [comment] 2022-11-27 16:19
Unfortunately I have the same issue but it seems very hard to replicate with a minimal config. However, blinking seems mostly fine for me if I stay at this previous commit:
```lua
    use({
      "nvim-zh/colorful-winsep.nvim",
      config = function()
        require("colorful-winsep").setup({})
      end,
      commit = "dbdf5ac62273385638c5ba9dd9017e9dd0fdb8d8",
    })

```

**Comment by denstiny** [comment] 2022-11-27 16:49
> Unfortunately I have the same issue but it seems very hard to replicate with a minimal config. However, blinking seems mostly fine for me if I stay at this previous commit:
> 
> ```lua
>     use({
>       "nvim-zh/colorful-winsep.nvim",
>       config = function()
>         require("colorful-winsep").setup({})
>       end,
>       commit = "dbdf5ac62273385638c5ba9dd9017e9dd0fdb8d8",
>     })
> ```

Whether it is caused by other plugins in the window window, I am not sure

**Comment by denstiny** [comment] 2022-11-27 17:07
This can only be resolved by the user, I can only help！

**Comment by distek** [comment] 2023-01-03 15:17
Weird observation:
- foot: this happens consistently
- alacritty: happens but is way less noticeable
- kitty: doesn't occur
- konsole: doesn't occur

Not sure why on any of the above, but thought it might be worth noting that it's different on different terminal emulators.

**Closed** 2023-01-14 11:40 UTC
Labels: bug, wontfix
